### ISSUE TITLE
Push new versions to Ansible Galaxy

### ISSUE THREAD

**Issue by AMeng** [silpion/ansible-tomcat#23]
Can we get the newest release pushed to Ansible Galaxy? The latest version available there is `1.3.0`.
https://galaxy.ansible.com/groover/tomcat/

**Comment by spul** [comment]
Hi, I'd love to do that, but this is somewhat political. galaxy today uses tight github integration. github API is quite limited for us in terms of what Ansible is allowed to do. For that reason it is not impossible that Galaxy can do things it should not be allowed to.

We discussed this on Ansiblefest in London, discussed this here at Silpion, ... No solution up to now.

Our workaround for that is to use requirements yaml pointing `src:` to github URL.

I fear there will be no quick solution for this particular issue here. I'll take it for another opportunity to create discussion at Silpion how to proceed with that, and have this issue kept open.

**Comment by AMeng** [comment]
That's understandable. The main issue with using `src:` with the github URL is that you don't get the dependency resolution. This role because particularly cumbersome as its dependencies have dependencies. So my requirements file looks something like:

```yaml
- src: https://github.com/silpion/ansible-lib
  name: silpion.lib
  version: 2.0.2
- src: https://github.com/silpion/ansible-util
  name: silpion.util
  version: 2.0.4
- src: https://github.com/silpion/ansible-tomcat
  name: groover.tomcat
  version: 2.1.0
```

Its now up to the end user to correctly manage this dependency chain.

One possible (but annoying) solution might be to create a separate GitHub organization that only hosts open source projects. Perhaps allowing galaxy access to that organization might be more acceptable.
