### ISSUE TITLE
"msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'general'"

### ISSUE THREAD

**Issue by aelkz** [silpion/ansible-tomcat#34]
Cant find a solution for this error.

Here's my playbook:

```
---
- hosts: server1
  vars:
    tomcat_version: 8.5.9
    tomcat_install_base: /srv
    tomcat_service_allow_restart: false
    tomcat_instances:
      - name: tomcat
        user: tomcat
        group: tomcat
        system: true
        service_name: tomcat
        service_file: tomcat.service
        prefer_ipv4: true
        prefer_urandom: true
        override_uri_encoding: UTF-8
  roles:
    - { role: tomcat }
```

**Comment by aelkz** [comment]
The following configuration are currently getting the same error:

```
---
- hosts: server1
  vars:
    tomcat_version: 8.5.9
    tomcat_service_allow_restart: true
    prefer_ipv4: true
    prefer_urandom: true
    override_uri_encoding: UTF-8
    tomcat_instances:
      - name: node1
        service_name: tomcat-node1
        service_file: tomcat-node1.conf
        port_ajp: 18009
        port_connector: 18080
        port_redirect: 18443
        port_shutdown: 18005
      - name: node2
        service_name: tomcat-node2
        service_file: tomcat-node2.conf
        port_ajp: 28009
        port_connector: 28080
        port_redirect: 28443
        port_shutdown: 28005
  roles:
    - { role: tomcat } 
```
